### ISSUE TITLE
Automatically transfer between CPU and GPU

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#1029]
* [ ] For EXLA
* [ ] For Torchx

@polvalente, can you tell us what happens if you have a tensor in the GPU and a tensor in the CPU and we try to add them together in Torchx?

@seanmor5, which type of automatic conversations we want to have? From `:host` to SOMETHING ELSE only? Everything else is explicit? If so, can you please add a low-level buffer API that does so? I can work on the Elixir logic itself.

**Comment by polvalente** [comment]
```elixir
iex(2)> t1 = Nx.tensor(1, backend: {Torchx.Backend, device: :mps})
#Nx.Tensor<
  s64
  Torchx.Backend(mps)
  1
>
iex(3)> t2 = Nx.tensor(1, backend: {Torchx.Backend, device: :cpu})
#Nx.Tensor<
  s64
  Torchx.Backend(cpu)
  1
>
iex(4)> Nx.add(t1, t2)
** (ArgumentError) cannot perform operation across devices cpu and mps
    (torchx 0.4.1) lib/torchx.ex:484: anonymous fn/2 in Torchx.prepare_tensors!/1
    (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (torchx 0.4.1) lib/torchx.ex:274: Torchx.add/2
    (torchx 0.4.1) lib/torchx/backend.ex:839: Torchx.Backend.add/3
iex(4)> Nx.add(t2, t1)
** (ArgumentError) cannot perform operation across devices mps and cpu
    (torchx 0.4.1) lib/torchx.ex:484: anonymous fn/2 in Torchx.prepare_tensors!/1
    (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (torchx 0.4.1) lib/torchx.ex:274: Torchx.add/2
    (torchx 0.4.1) lib/torchx/backend.ex:839: Torchx.Backend.add/3
```

libtorch doesn't do automatic transfers between devices
