### ISSUE TITLE
unknown client :rocm given as :preferred_clients

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-nx/nx#1038]
I recently upgraded my bumblebee version and now I get this exception:

```
    ** (EXIT) an exception was raised:
        ** (RuntimeError) unknown client :rocm given as :preferred_clients
            (exla 0.4.1) lib/exla/client.ex:31: anonymous fn/3 in EXLA.Client.default_name/0
            (elixir 1.14.1) lib/enum.ex:4211: Enum.find_list/3
            (exla 0.4.1) lib/exla/client.ex:28: EXLA.Client.default_name/0
            (exla 0.4.1) lib/exla/backend.ex:147: EXLA.Backend.client_and_device_id/1
            (exla 0.4.1) lib/exla/backend.ex:44: EXLA.Backend.from_binary/3
            (bumblebee 0.1.2) lib/bumblebee/layers/clip.ex:106: Bumblebee.Layers.Clip.attention/4
            (bumblebee 0.1.2) lib/bumblebee/layers/clip.ex:57: Bumblebee.Layers.Clip.encoder_block/4
            (bumblebee 0.1.2) lib/bumblebee/layers/clip.ex:35: anonymous fn/6 in Bumblebee.Layers.Clip.encoder_blocks/4
            (elixir 1.14.1) lib/enum.ex:4299: Enum.reduce_range/5
            (bumblebee 0.1.2) lib/bumblebee/text/clip_text.ex:157: Bumblebee.Text.ClipText.text_transformer/5
            (bumblebee 0.1.2) lib/bumblebee/text/clip_text.ex:119: Bumblebee.Text.ClipText.model/1
            (bumblebee 0.1.2) lib/bumblebee.ex:376: Bumblebee.load_model/2
```

Here is my configuration:

``` elixir
config :nx, default_backend: EXLA.Backend
config :exla,
  clients: [
    cuda: [platform: :cuda]
  ]
```

**Comment by krainboltgreene** [comment]
Ugh, okay, other than the confusing error messages here (that didn't happen before), this is because I recompiled without the XLA_TARGET env.

Maybe exla (or elixir) should store the relevant (or all) ENVs on compile and warn if a recompile would change the build?
