### ISSUE TITLE
Nx.deserialize errors when run in different notebook and backend_transfer issue

### ISSUE THREAD

**Issue by meanderingstream** [elixir-nx/nx#1079]
serialize/deserialize works in a single notebook.  However when default_backend is exla or torchx deserialize results in error.  One notebooks serializes map_container = %{x: Nx.iota({2, 2, 3}, type: :f32), y: Nx.iota({20}, type: :f32)} and saves to a file.  The second notebook reads the file and deserializes it back into %{x: x, y: y}  The error is:

** (UndefinedFunctionError) function EXLA.Backend.from_binary/3 is undefined (module EXLA.Backend is not available)
    EXLA.Backend.from_binary(#Inspect.Error<
  got KeyError with message:

      """
      key :__struct__ not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
      """

  while inspecting:

      %{__struct__: Nx.Tensor, data: nil, names: [nil], shape: {12}, type: {:f, 32}}

  Stacktrace:

    (nx 0.4.2) lib/nx/tensor.ex:165: Inspect.Nx.Tensor.inspect/2
    (elixir 1.14.2) lib/inspect/algebra.ex:341: Inspect.Algebra.to_doc/2
    (elixir 1.14.2) lib/kernel.ex:2254: Kernel.inspect/2
    (elixir 1.14.2) lib/exception.ex:719: anonymous fn/2 in Exception.format_arity/1
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.2) lib/exception.ex:719: Exception.format_arity/1
    (elixir 1.14.2) lib/exception.ex:714: Exception.format_mfa/3
    (elixir 1.14.2) lib/exception.ex:625: Exception.format_stacktrace_entry/1

If the backend is BinaryBackend, this process works just fine.  It is only when using the CPU version of torchx and exla that I've found an issue.  BinaryBackend can load the files created by exla and probably by torchx.  I didn't test this capability.

Also, Nx.backend_transfer(x, {EXLA.Backend, client: :host}) from the BinaryBackend fails with:
** (UndefinedFunctionError) function EXLA.Backend.from_binary/3 is undefined (module EXLA.Backend is not available)
    EXLA.Backend.from_binary(#Nx.Tensor<
  f32[2][2][3]
  [
    [
      [0.0, 1.0, 2.0],
      [3.0, 4.0, 5.0]
    ],
    [
      [6.0, 7.0, 8.0],
      [9.0, 10.0, 11.0]
    ]
  ]
>, <<0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 64, 0, 0, 64, 64, 0, 0, 128, 64, 0, 0, 160, 64, 0, 0, 192, 64, 0, 0, 224, 64, 0, 0, 0, 65, 0, 0, 16, 65, 0, 0, 32, 65, 0, 0, 48, 65>>, [client: :host])
    (nx 0.4.2) lib/nx/defn/composite.ex:101: anonymous fn/3 in Nx.Defn.Composite.traverse/2
    (nx 0.4.2) lib/nx/defn/composite.ex:101: Nx.Defn.Composite.traverse/2
    /home/ml3/local_apps/livebook/training_w_axon/prototypes/file_serialization/file-deserialization-exla-via-binary.livemd#cell:igkiha26kkw5b5xlqbofyrbilqfzpyay:1: (file)

**Comment by meanderingstream** [comment]
I pulled the section on backend transfer issue.  I can get deserialization working when using BinaryBackend against the BinaryBackend saved file and then 
 Nx.backend_transfer(x, {EXLA.Backend, client: :host}) or
 Nx.backend_transfer(%{x: x, y: y}, {EXLA.Backend, client: :host})

**Comment by polvalente** [comment]
Do you have a minimal code to reproduce this issue?
Ideally, the code for both notebooks

**Comment by meanderingstream** [comment]
I'll work on that.  I've now found that the issue is caused when Nx.default_backend is set to any appropriate backend in the second notebook.  If I set the default_backend before the File.read and deserialize then deserialize fails.  Even if I explicitly set BinaryBackend, deserialize fails.

**Comment by meanderingstream** [comment]
First notebook:
map_container = %{x: Nx.iota({2, 2, 3}, type: :f32), y: Nx.iota({20}, type: :f32)}
serialized_binary =
  Nx.serialize(map_container)
  |> IO.iodata_to_binary()
cache_dir = "cache/snacks/tmp/binary/"
File.mkdir_p!(cache_dir)
{:ok, file} = File.open(cache_dir <> "1.serial", [:write])
IO.binwrite(file, serialized_binary)
File.close(file)
File.exists?(cache_dir <> "1.serial")

**Comment by josevalim** [comment]
@meanderingstream does the second notebook include the dependency to EXLA/Torchx before you set them as a backend and/or before you try to deserialize it?

**Comment by meanderingstream** [comment]
Yes.  My setup is:
Mix.install([
  {:torchx, "~> 0.4.2"},
  {:nx_image, "~> 0.1.0"},
  {:stb_image, "~> 0.6.0"}
])

Or with exla

**Comment by josevalim** [comment]
Should this:

```elixir
 Nx.default_backend({BinaryBackend, []})
```

be:

```elixir
 Nx.default_backend({Nx.BinaryBackend, []})
```

or are you aliasing it before?

**Comment by josevalim** [comment]
Btw, Nx v0.5 will raise a better error if you try to use a backend that does not exist (or has the wrong name).

**Comment by josevalim** [comment]
FWIW, the second code for the second notebook works for me with both `EXLA.Backend` and `Nx.BinaryBackend`.

**Comment by meanderingstream** [comment]
So that fixed the issue for BinaryBackend and Torchx.  Therefore, I must not know how to set cpu for EXLA.Backend
Nx.default_backend({EXLA.Backend, client: :cpu})

**Comment by meanderingstream** [comment]
Setting to Nx.default_backend({EXLA.Backend, client: :host}) allows the binary, torchx, and exla files to be loaded.  Therefore, this issue can be closed.

However, one more comment,  Will setting the default_backend be changed to return the new backend also?

**Comment by meanderingstream** [comment]
Closing the issue because the root of the problem was the misunderstanding of setting the default_backend.

**Comment by josevalim** [comment]
Better error message will also come on v0.5 :)
