### ISSUE TITLE
Raise with 'if' and 'Nx.all/any'

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#1099]
I don't know this is bug or feature, but this code

```elixir
defmodule T do
  import Nx.Defn
  defn foo() do
    Nx.greater(1, 2)
    |> Nx.all() # raises only with this line
    |> if do raise "error" end
  end
end
T.foo()
```

raises

```
** (RuntimeError) error
    #cell:imqhow2x6lgpgnqbedwnqj7tfbqmroc7:6: anonymous fn/0 in T."__defn:foo__"/0
    (nx 0.5.0) lib/nx/defn/expr.ex:296: Nx.Defn.Expr.defn_cond/2
    (nx 0.5.0) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (exla 0.5.0) lib/exla/defn.ex:385: anonymous fn/4 in EXLA.Defn.compile/8
    (exla 0.5.0) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 3.17.2) timer.erl:166: :timer.tc/1
    (exla 0.5.0) lib/exla/defn.ex:383: EXLA.Defn.compile/8
    (exla 0.5.0) lib/exla/defn.ex:270: EXLA.Defn.__compile__/4
```

**Comment by josevalim** [comment]
This is expected but it is confusing. All clauses in `if` are evaluated at compile-time to build the expression.  Especially because _you cannot raise on the GPU_.  I will improve the docs.

**Comment by josevalim** [comment]
More info: https://hexdocs.pm/nx/Nx.Defn.Kernel.html#raise/2
