### ISSUE TITLE
torchx: process_begin: CreateProcess(NULL, pwd, ...) failed. Makefile:29: pipe: No such file or directory

### ISSUE THREAD

**Issue by wojtekmach** [elixir-nx/nx#1123]
I tried adding a "Neural Network task" to a latest nightly Livebook Desktop on Windows and got a compilation error on torchx. I was able to reproduce it by just Mix installing torchx:

```elixir
Mix.install([
  {:torchx, "~> 0.5.1"}
])
```

```
(...)
==> torchx
process_begin: CreateProcess(NULL, pwd, ...) failed.
Makefile:29: pipe: No such file or directory
process_begin: CreateProcess(NULL, pwd, ...) failed.
Makefile:29: pipe: No such file or directory
could not compile dependency :torchx, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile torchx", update it with "mix deps.update torchx" or clean it with "mix deps.clean torchx"
```

**Comment by mohammedzeglam-pg** [comment]
i have alot of issue libtorch download and this and alot just a pain

**Comment by polvalente** [comment]
@wojtekmach I'm not familiar with the internals of livebook desktop. Which shell does it use? Is it plain cmd or powershell, or is it WSL?

It seems to me that the most probable issue is that somehow elixir_make decided to use `Makefile` instead of `Makefile.win`

**Comment by polvalente** [comment]
@josevalim I tried reproducing this but I get a different issue.
Trying to install from hex with "~> 0.5" works fine.
However, if I try to run from the git repo with `iex -S mix`, I get this error:

```
Interactive Elixir (1.14.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Nx.tensor(1, backend: Torchx.Backend)
** (UndefinedFunctionError) function Torchx.NIF.cuda_is_available/0 is undefined (module Torchx.NIF is not available)
    (torchx 0.5.1) Torchx.NIF.cuda_is_available()
    (elixir 1.14.4) lib/enum.ex:4211: Enum.find_list/3
    (torchx 0.5.1) lib/torchx.ex:208: Torchx.default_device/0
    (torchx 0.5.1) lib/torchx/backend.ex:66: Torchx.Backend.constant/3
    iex:1: (file)
iex(1)>
00:13:32.207 [error] Process #PID<0.252.0> raised an exception
** (UndefinedFunctionError) function DLLLoaderHelper.addDLLDirectory/1 is undefined (module DLLLoaderHelper is not available)
    (dll_loader_helper 0.1.0) DLLLoaderHelper.addDLLDirectory("c:/Users/valente/Desktop/nx/torchx/_build/dev/lib/torchx/priv/libtorch")
    (torchx 0.5.1) lib/torchx/nif.ex:7: Torchx.NIF.__on_load__/0
    (kernel 8.5.4) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
iex(1)>
00:13:32.207 [warning] The on_load function for module Elixir.DLLLoaderHelper returned:
{:error,
 {:load_failed,
  'Failed to load NIF library c:/Users/valente/Desktop/nx/torchx/_build/dev/lib/dll_loader_helper/priv/dll_loader_helper: \'Unspecified error\''}}

iex(1)>
00:13:32.210 [warning] The on_load function for module Elixir.Torchx.NIF returned:
{:undef,
 [
   {DLLLoaderHelper, :addDLLDirectory,
    ["c:/Users/valente/Desktop/nx/torchx/_build/dev/lib/torchx/priv/libtorch"],
    []},
   {Torchx.NIF, :__on_load__, 0, [file: 'lib/torchx/nif.ex', line: 7]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', ...]}
 ]}
```

What's even weirder is that `Mix.install [{:torchx, path: "."}]` instead works as well.

**Comment by josevalim** [comment]
@polvalente it seems none of the NIFs are getting loaded with Git. Perhaps something with the path. However, if it works on Hex for now and we cannot reproduce, I think we can move forward.
