### ISSUE TITLE
SVD does not support :f16 and :bf16 types

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#1177]
The following code generates error:

```elixir
x = Nx.tensor([[1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4]], type: :f16)
Nx.LinAlg.svd(x)
```

```
** (CompileError) /home/mateusz/.cache/mix/installs/elixir-1.14.2-erts-13.1.4/4d1435fa13ffc3d4da040c8406b8311c/deps/nx/lib/nx/lin_alg/svd.ex:170: the do-block in while must return tensors with the same shape, type, and names as the initial arguments.

Body matches template:

{#Nx.Tensor<
   f32[4][4]
 >, #Nx.Tensor<
   f32
 >, #Nx.Tensor<
   s64
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   s64
 >}

and initial argument has template:

{#Nx.Tensor<
   f16[4][4]
 >, #Nx.Tensor<
   f32
 >, #Nx.Tensor<
   s64
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   s64
 >}

    (nx 0.5.2) lib/nx/defn/expr.ex:483: Nx.Defn.Expr.compatible_while!/4
    (nx 0.5.2) lib/nx/defn/expr.ex:354: Nx.Defn.Expr.defn_while/6
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:170: Nx.LinAlg.SVD."__defn:qdwh__"/2
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:140: Nx.LinAlg.SVD."__defn:svd_tall_and_square__"/2
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:76: Nx.LinAlg.SVD."__defn:svd_full__"/2
    (nx 0.5.2) lib/nx/lin_alg/svd.ex:1: Nx.LinAlg.SVD."__defn:svd_non_zero__"/2
    (nx 0.5.2) lib/nx/defn/expr.ex:300: anonymous fn/4 in Nx.Defn.Expr.defn_cond/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by msluszniak** [comment]
The same problem is with `:bf16`

**Comment by msluszniak** [comment]
And `Nx.LinAlg.pinv` also does not work since it uses SVD.

**Comment by polvalente** [comment]
This is because the default implementation (that we use for EXLA and BinaryBackend) only supports f32 in the calculation itself.

I'll send a PR doing a typecast on the input and output to solve this once #1168 is merged
