### ISSUE TITLE
[EXLA] while inside if doesn't work with containers within defn

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#1190]
```elixir
iex(13)> defmodule M do
...(13)>   import Nx.Defn
...(13)>     
...(13)>   defn f(pred, x) do
...(13)>     if pred do
...(13)>       {x, _} = 
...(13)>         while {x, i = 0}, i < 10 do
...(13)>           {x, i + 1}
...(13)>         end
...(13)>         
...(13)>       x
...(13)>     else
...(13)>       x
...(13)>     end
...(13)>   end
...(13)> end
warning: redefining module M (current version defined in memory)
  iex:13

{:module, M,
 <<70, 79, 82, 49, 0, 0, 11, 84, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 128,
   0, 0, 0, 34, 8, 69, 108, 105, 120, 105, 114, 46, 77, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 10, 97, 116, 116, 114, ...>>, true}
iex(14)> M.f(1, %{a: 1, b: 2.0})
** (RuntimeError) the result of branch 0 computation and branch 1 computation must have the same shape: got branch 0 computation result: (token[], (s64[], f32[], s64[])); branch 1 computation result: (token[], (s64[], f32[])).
    (exla 0.5.2) lib/exla/op.ex:855: EXLA.Op.unwrap!/1
    (exla 0.5.2) lib/exla/op.ex:109: EXLA.Op.get_shape/1
    (exla 0.5.2) lib/exla/builder.ex:23: EXLA.Builder.build/1
    (exla 0.5.2) lib/exla/defn.ex:310: EXLA.Defn.to_root_computation/5
    (exla 0.5.2) lib/exla/defn.ex:423: anonymous fn/11 in EXLA.Defn.compile/8
    (exla 0.5.2) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    iex:14: (file)
```

from the `f32[]` shape we can see that while the `else` expects just the 2 values in the container to be returned, the while is also returning the `i` value as well. 

Absorbing the `pred` condition into the `while` predicate is a possible workaround until we fix this

**Comment by polvalente** [comment]
using `cond` and the generator-version of while with `unroll: true` I was able to compile correctly. Haven't tested much more than this
