### ISSUE TITLE
Issue when trying to do multidevice setup.

### ISSUE THREAD

**Issue by enzoqtvf** [elixir-nx/nx#1202]
Hey team ! :)

I currently have an issue when trying to do multidevice setup, let me try to describe the issue I face and the setup I have :).

I use:
- docker image rocm/tensorflow:latest
- nx 0.5.3
- exla 0.5.3
- xla 0.4.4
- bumblebee 0.3.0

I do have 8 rocm devices available (I can see them fine when the application runs).
In my config.ex I do have:
```
config :nx, default_backend: EXLA.Backend
```

I'm using bumblebee to load openai-whisper model and I do it this way in my application:
```
    {:ok, model_info} = Bumblebee.load_model({:hf, "openai/whisper-tiny"})

    {:ok, featurizer} = Bumblebee.load_featurizer({:hf, "openai/whisper-tiny"})
    {:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, "openai/whisper-tiny"})
    {:ok, generation_config} = Bumblebee.load_generation_config({:hf, "openai/whisper-tiny"})

    serving =
      Bumblebee.Audio.speech_to_text(model_info, featurizer, tokenizer, generation_config,
        compile: [batch_size: 10],
        defn_options: [compiler: EXLA]
      )
```

Then I start in my supervisor childrens:
```
{Nx.Serving, serving: serving, name: Whisper.Serving, partitions: true},
```
(note the partitions: true)

From there I run it using:
```
Nx.Serving.batched_run(Whisper.Serving, {:file, "wav_files/test.wav"})
```

This works fine 1/8 of the time, the rest of the time I get this:
```
14:51:13.259 [error] Task #PID<0.854.0> started from Whisper.Serving terminating
** (RuntimeError) Expected buffer to be placed on device 2
    (exla 0.5.3) lib/exla/executable.ex:56: EXLA.Executable.unwrap!/1
    (exla 0.5.3) lib/exla/executable.ex:19: EXLA.Executable.run/3
    (exla 0.5.3) lib/exla/defn.ex:346: EXLA.Defn.maybe_outfeed/7
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (exla 0.5.3) lib/exla/defn.ex:283: anonymous fn/7 in EXLA.Defn.__compile__/4
    (nx 0.5.3) lib/nx/defn.ex:313: anonymous fn/4 in Nx.Defn.compile/3
    (nx 0.5.3) lib/nx/serving.ex:1107: anonymous fn/2 in Nx.Serving.Default.handle_batch/3
    (nx 0.5.3) lib/nx/serving.ex:957: anonymous fn/3 in Nx.Serving.server_task_or_enqueue/3
Function: #Function<14.1903805/0 in Nx.Serving.server_task_or_enqueue/3>
    Args: []
** (exit) exited in: Nx.Serving.local_batched_run(Whisper.Serving, {:file, "wav_files/test.wav"})
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Expected buffer to be placed on device 2
            (exla 0.5.3) lib/exla/executable.ex:56: EXLA.Executable.unwrap!/1
            (exla 0.5.3) lib/exla/executable.ex:19: EXLA.Executable.run/3
            (exla 0.5.3) lib/exla/defn.ex:346: EXLA.Defn.maybe_outfeed/7
            (stdlib 4.0.1) timer.erl:235: :timer.tc/1
            (exla 0.5.3) lib/exla/defn.ex:283: anonymous fn/7 in EXLA.Defn.__compile__/4
            (nx 0.5.3) lib/nx/defn.ex:313: anonymous fn/4 in Nx.Defn.compile/3
            (nx 0.5.3) lib/nx/serving.ex:1107: anonymous fn/2 in Nx.Serving.Default.handle_batch/3
            (nx 0.5.3) lib/nx/serving.ex:957: anonymous fn/3 in Nx.Serving.server_task_or_enqueue/3
    (nx 0.5.3) lib/nx/serving.ex:620: Nx.Serving.local_batched_run!/3
    iex:16: (file)
```
[
I opened a thread in elixir slack channel](https://elixir-lang.slack.com/archives/C01M2B96EF9/p1681899663593099) where I got very helpful comments from @polvalente  (thanks again :))

I tried few things:
1. Tried to load the model this way instead:
```
    {:ok, model_info} =
      Nx.with_default_backend({EXLA.Backend, client: :host}, fn ->
        Bumblebee.load_model({:hf, "openai/whisper-tiny"})
      end)
```
but got no luck with that, same issue :/
2. Tried to use lazy_transfers option, but that was erasing data on the device_0 and failing 1/8 of the time as well with data rotating from a device to another
3. Tried to add Nx.backend_copy this way: 
```
Nx.Serving.batched_run(Whisper.Serving, {:file, file_path}, &Nx.backend_copy/1)
```
but no luck either :/ 

If anyone has an idea about what I'm doing wrong I would be happy to know :) 
Thank you very much everyone !

**Comment by josevalim** [comment]
@enzoqtvf you can make it work for now by forcing the host as your default client:

    config :nx, default_backend: {EXLA.Backend, client: :host}

And then from host we can transfer to the appropriate device.
