### ISSUE TITLE
Can't Compile EXNA: Eigen/Core file not found ( Big Sur 11.7.3 )

### ISSUE THREAD

**Issue by julienmarie** [elixir-nx/nx#1334]
## Log: 
```$ mix deps.compile exla
==> exla
c++ -fPIC -I/Users/julienmarie/.asdf/installs/erlang/25.2.1/erts-13.1.4/include -Icache/xla_extension/include -O3 -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -shared -std=c++17 -w -DLLVM_VERSION_STRING= c_src/exla/exla.cc c_src/exla/exla_nif_util.cc c_src/exla/exla_client.cc -o cache/libexla.so -Lcache/xla_extension/lib -lxla_extension -flat_namespace -undefined suppress
In file included from c_src/exla/exla.cc:3:
In file included from c_src/exla/exla_nif_util.h:13:
cache/xla_extension/include/xla/types.h:27:10: fatal error: 'Eigen/Core' file not found
#include "Eigen/Core"  // from @eigen_archive
         ^~~~~~~~~~~~
1 error generated.
In file included from c_src/exla/exla_nif_util.cc:1:
In file included from c_src/exla/exla_nif_util.h:13:
cache/xla_extension/include/xla/types.h:27:10: fatal error: 'Eigen/Core' file not found
#include "Eigen/Core"  // from @eigen_archive
         ^~~~~~~~~~~~
1 error generated.
In file included from c_src/exla/exla_client.cc:1:
In file included from c_src/exla/exla_client.h:8:
In file included from c_src/exla/exla_nif_util.h:13:
cache/xla_extension/include/xla/types.h:27:10: fatal error: 'Eigen/Core' file not found
#include "Eigen/Core"  // from @eigen_archive
         ^~~~~~~~~~~~
1 error generated.
make: *** [cache/libexla.so] Error 1
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"
==> karajan
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.

```

### Elixir: 
```
$ elixir -v
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```

### OS / Machine : 
```
Big Sur 11.7.3 (20G1116)
3.8 GHz 8-Core Intel Xeon W
64 GB RAM
```

### GCC: 
```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### MAKE:
```
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

### PROTOBUF unlinked already:
```
$ protobuf
zsh: command not found: protobuf
```

**Comment by polvalente** [comment]
How are you installing EXLA?

**Comment by julienmarie** [comment]
Simple way, via mix.exs:
```
 {:bumblebee, "~> 0.4.2"},
 {:nx, "~> 0.6.1"},
 {:exla, "~> 0.6.1"},
 {:axon, "~> 0.6.0"}
 ```
 
 Fixed it. Bazel was not installed.
 But now I have:
 ```
 ==> exla
Unpacking /Users/julienmarie/Library/Caches/xla/0.5.1/cache/download/xla_extension-x86_64-darwin-cpu.tar.gz into /Users/julienmarie/Code/cmdv/karajan/deps/exla/cache
c++ -fPIC -I/Users/julienmarie/.asdf/installs/erlang/25.2.1/erts-13.1.4/include -Icache/xla_extension/include -O3 -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -shared -std=c++17 -w -DLLVM_VERSION_STRING= c_src/exla/exla.cc c_src/exla/exla_nif_util.cc c_src/exla/exla_client.cc -o cache/libexla.so -Lcache/xla_extension/lib -lxla_extension -flat_namespace -undefined suppress
In file included from c_src/exla/exla.cc:4:
In file included from c_src/exla/exla_client.h:12:
In file included from cache/xla_extension/include/xla/pjrt/pjrt_client.h:33:
cache/xla_extension/include/mlir/IR/BuiltinOps.h:16:10: fatal error: 'mlir/Bytecode/BytecodeOpInterface.h' file not found
#include "mlir/Bytecode/BytecodeOpInterface.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from c_src/exla/exla_client.cc:1:
In file included from c_src/exla/exla_client.h:12:
In file included from cache/xla_extension/include/xla/pjrt/pjrt_client.h:33:
cache/xla_extension/include/mlir/IR/BuiltinOps.h:16:10: fatal error: 'mlir/Bytecode/BytecodeOpInterface.h' file not found
#include "mlir/Bytecode/BytecodeOpInterface.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [cache/libexla.so] Error 1
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"
==> karajan
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

**Comment by polvalente** [comment]
Try removing your build and cache directories just so we can ensure there's no previous version of libexla.so interfering

**Comment by julienmarie** [comment]
Fixed it. 
Had to install GCC 8 and then
```
export CC=/usr/local/Cellar/gcc@8/8.5.0/bin/gcc-8
``` 
then deps.clean / deps.compile

**Comment by julienmarie** [comment]
And now another error when launching the app:

```
[warning] The on_load function for module Elixir.EXLA.NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/julienmarie/Code/cmdv/karajan/_build/dev/lib/exla/priv/libexla.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allo
catorIcEEE3strEv\n  Referenced from: /Users/julienmarie/Code/cmdv/karajan/_build/dev/lib/exla/priv/xla_extension/lib/libxla_extension.so (which was built for Mac OS X 13.1)\n  Expected in: /usr/
lib/libc++.1.dylib\n\''}}
```

```

[notice] Application image exited: exited in: Image.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function EXLA.NIF.get_supported_platforms/0 is undefined (module EXLA.NIF is not available)
            (exla 0.6.1) EXLA.NIF.get_supported_platforms()
            (exla 0.6.1) lib/exla/client.ex:80: EXLA.Client.get_supported_platforms/0
            (exla 0.6.1) lib/exla/client.ex:28: EXLA.Client.default_name/0
            (exla 0.6.1) lib/exla/backend.ex:154: EXLA.Backend.client_and_device_id/1
            (exla 0.6.1) lib/exla/backend.ex:44: EXLA.Backend.from_binary/3
            (bumblebee 0.4.2) lib/bumblebee/conversion/pytorch/loader.ex:79: Bumblebee.Conversion.PyTorch.Loader.object_resolver/1
            (unpickler 0.1.0) lib/unpickler.ex:828: Unpickler.resolve_object/2
            (unpickler 0.1.0) lib/unpickler.ex:818: anonymous fn/2 in Unpickler.finalize_stack_items/2
            (elixir 1.14.3) lib/map.ex:924: Map.get_and_update/3
            (elixir 1.14.3) lib/map.ex:966: Map.get_and_update!/3
            (unpickler 0.1.0) lib/unpickler.ex:818: anonymous fn/2 in Unpickler.finalize_stack_items/2
            (elixir 1.14.3) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
            (unpickler 0.1.0) lib/unpickler.ex:525: Unpickler.load_op/3
            (bumblebee 0.4.2) lib/bumblebee/conversion/pytorch/loader.ex:53: Bumblebee.Conversion.PyTorch.Loader.load_zip!/1
            (bumblebee 0.4.2) lib/bumblebee/conversion/pytorch.ex:48: anonymous fn/2 in Bumblebee.Conversion.PyTorch.load_params!/4
            (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
            (bumblebee 0.4.2) lib/bumblebee/conversion/pytorch.ex:47: anonymous fn/4 in Bumblebee.Conversion.PyTorch.load_params!/4
            (bumblebee 0.4.2) lib/bumblebee.ex:518: Bumblebee.load_params/5
            (bumblebee 0.4.2) lib/bumblebee.ex:490: Bumblebee.load_model/2
            (image 0.38.0) lib/image/classification.ex:128: Image.Classification.serving/2
```

**Comment by polvalente** [comment]
This one looks like you're linking against the wrong libc version. Probably related to the way you had to export a specific path for gcc

**Comment by julienmarie** [comment]
... i'll give up for now. I'll look into it when I have more time.
