### ISSUE TITLE
Nx.Serving crashes due to empty stack

### ISSUE THREAD

**Issue by samrat** [elixir-nx/nx#1347]
Hello,

I'm seeing a crash with the following stacktrace. This happens a few minutes/hours of my application running and I'm not sure what exactly triggers it.

```
[error] GenServer #PID<0.603.0> terminating
** (stop) exited in: Nx.Serving.local_batched_run(SentenceTransformer, "test string")
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Nx.Serving.handle_info/2
            (nx 0.6.2) lib/nx/serving.ex:1406: anonymous fn({[], 0, :none}) in Nx.Serving.handle_info/2
            (nx 0.6.2) lib/nx/serving.ex:1622: Nx.Serving.stack_update/2
            (nx 0.6.2) lib/nx/serving.ex:1406: Nx.Serving.handle_info/2
            (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
            (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
            (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (nx 0.6.2) lib/nx/serving.ex:992: Nx.Serving.local_batched_run!/3
    (daymar 0.1.0) lib/daymar/embedding_worker.ex:25: Daymar.EmbeddingWorker.get_embedding/1
    (daymar 0.1.0) lib/daymar/embedding_worker.ex:45: anonymous fn/2 in Daymar.EmbeddingWorker.process_rows/0
    (elixir 1.15.7) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (daymar 0.1.0) lib/daymar/embedding_worker.ex:20: Daymar.EmbeddingWorker.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:notification, #PID<0.604.0>, #Reference<0.3824733576.2547777538.181563>, "embeddings", "post_inserted"}
```

It seems in https://github.com/elixir-nx/nx/blob/2854998a70bbe9385a73567390d2bd687616d9ef/nx/lib/nx/serving.ex#L1406 the fn expects a non-empty list but it is getting passed an empty stack.

**Comment by josevalim** [comment]
Can you tell me your serving configuration? I think a combination of events is leading to this and knowing the batch size and the size of batches you use will be very helpful. :)

**Comment by josevalim** [comment]
Actually, I think I found out the root cause to be stray timer messages. Can you give branch v0.6 a try? And if it all works I can ship a new release.
