### ISSUE TITLE
Issue with broadcast and vectorized axes on v0.6.4

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#1383]
```elixir
defmodule Test do
  import Nx.Defn

  defn test(input) do
    Nx.broadcast(input[0], Nx.shape(input), names: Nx.names(input))
  end
end

iex> Nx.iota({2}, names: [:b]) |> Test.test()
#Nx.Tensor<
  s64[b: 2]
  [0, 0]
>

iex> Nx.iota({2, 2}, names: [:a, :b]) |> Nx.vectorize(:a) |> Test.test()
** (ArgumentError) cannot broadcast tensor of dimensions {} to {2} with axes []
    (nx 0.6.4) lib/nx/shape.ex:253: Nx.Shape.broadcast!/4
    (nx 0.6.4) lib/nx.ex:3863: anonymous fn/4 in Nx.broadcast/3
    (nx 0.6.4) lib/nx.ex:5461: Nx.apply_vectorized/2
    (nx 0.6.4) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (nx 0.6.4) lib/nx/defn/evaluator.ex:83: Nx.Defn.Evaluator.precompile/3
    (nx 0.6.4) lib/nx/defn/evaluator.ex:61: Nx.Defn.Evaluator.__compile__/4
    (nx 0.6.4) lib/nx/defn/evaluator.ex:54: Nx.Defn.Evaluator.__jit__/5
    iex:4: (file)
```

**Comment by polvalente** [comment]
Looking into this
