### ISSUE TITLE
Nx.all_close not working with EXLA

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/nx#1430]
```
Nx.default_backend(EXLA.Backend)
a = Nx.tensor([1, 2, 3])
b = Nx.tensor([1, 2, 3])
Nx.all_close(a, b)
```
gives
```
** (MatchError) no match of right hand side value: [#Nx.Tensor<
    u8
    
    Nx.Defn.Expr
    parameter a:0                                                      s64[3]
    parameter b:1                                                      s64[3]
    c = all_close a, b, atol: 1.0e-8, rtol: 1.0e-5, equal_nan: false   u8
  >, #Nx.Tensor<
    u8
    
    Nx.Defn.Expr
    parameter a:0                            s64[3]
    parameter b:1                            s64[3]
    c = subtract a, b                        s64[3]
    d = abs c                                s64[3]
    e = abs b                                s64[3]
    f = multiply 1.0e-5, e                   f32[3]
    g = add 1.0e-8, f                        f32[3]
    h = less_equal d, g                      u8[3]
    i = all h, axes: nil, keep_axes: false   u8
  >, #Function<6.59455918/3 in Nx.vectorized_all_close>]
    (exla 0.6.3) lib/exla/defn.ex:557: EXLA.Defn.cached_recur_operator/4
    (exla 0.6.3) lib/exla/defn.ex:486: EXLA.Defn.recur_operator/3
    (exla 0.6.3) lib/exla/defn.ex:473: anonymous fn/3 in EXLA.Defn.recur_flatten/3
    (exla 0.6.3) lib/exla/defn.ex:472: EXLA.Defn.recur_flatten/3
    (exla 0.6.3) lib/exla/defn.ex:308: EXLA.Defn.to_root_computation/5
    (exla 0.6.3) lib/exla/defn.ex:427: anonymous fn/11 in EXLA.Defn.compile/8
    (exla 0.6.3) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    iex:5: (file)
```
Is this intended?

**Comment by jonatanklosko** [comment]
It works fine standalone, can you minimize the defn example that still reproduces it?

**Comment by jonatanklosko** [comment]
You can also try nx/exla main just in case :)

**Comment by jonatanklosko** [comment]
You can try `mix deps.update exla`. Currently it's locked at 0.6.3, but maybe 0.6.4 fixed it. Otherwise we need to depend on exla main in `mix.exs` I guess.

**Comment by josevalim** [comment]
@krstopro make sure you use main for both, if using main. If using a package, do `mix deps.update nx exla`.

**Comment by krstopro** [comment]
Upgraded to 0.6.4, didn't resolve it.

**Comment by krstopro** [comment]
`Nx.all_close/3` is used all over Scholar as it is used to implement `assert_all_close` which is behind many unit tests.
https://github.com/elixir-nx/scholar/blob/6c609685db1f5808945425468019d993e06597b4/test/support/scholar_case.ex#L16
Which means it's probably me that made an error somewhere...

**Comment by josevalim** [comment]
Can you share your mix.lock?

**Comment by krstopro** [comment]
Right now it's the same as in main of Scholar
https://github.com/elixir-nx/scholar/blob/main/mix.lock
If I do `mix deps.update nx exla` unit tests will fail.

**Comment by josevalim** [comment]
Yeah, as I said above, you need to swap exla to use github as well, since nx is pointing to github. It just happens that the commit it is currently locked on did not diverge. Btw, why do you need to bump nx?

**Comment by krstopro** [comment]
> Yeah, as I said above, you need to swap exla to use github as well, since nx is pointing to github. It just happens that the commit it is currently locked on did not diverge. Btw, why do you need to bump nx?

Didn't need to, just copied what you wrote [above](https://github.com/elixir-nx/nx/issues/1430#issuecomment-1863007216) and forgot to remove nx. 😅

**Comment by josevalim** [comment]
Ok, I think we can close this one then. Scholar worked for me once both are on git and updated to latest. :D
