### ISSUE TITLE
Nx.Defn.Grad returns sum of gradient over vectorized axis?

### ISSUE THREAD

**Issue by jyc** [elixir-nx/nx#1533]
Thanks for making Nx!

I tried to use `value_and_grad` on a function that takes two inputs: a vectorized tensor and a non-vectorized tensor.

``` elixir
defmodule Foo do
  import Nx.Defn
  defn f(x, y) do
    x + y
  end

  defn f_and_grad(x, y) do
    value_and_grad(y, fn y -> Foo.f(x, y) end)
  end
end

x = ~VEC[0 1] |> vectorize(:bar)
Foo.f_and_grad(x, 1)
```

This evaluates to:

```
{#Nx.Tensor<
   vectorized[bar: 2]
   s64
   EXLA.Backend<host:0, 0.731981912.321781778.128426>
   [1, 2]
 >,
 #Nx.Tensor<
   f32
   EXLA.Backend<host:0, 0.731981912.321781778.128427>
   2.0
 >}
```

The value is correct and maintains the vectorized axis of the vectorized input to `x`, but the gradient surprises me. I would have expected a vectorized tensor rank-1 dimension-2 vector with the same `:foo` axis and which is everywhere `1`; it looks like instead Nx is summing up the two gradients.

Is this behavior expected? If so, is there any way to make Nx return a vectorized gradient?

Thanks!

**Comment by jyc** [comment]
I know that I can use

```elixir
y = ~VEC[1 1] |> vectorize(:bar)
Foo.f_and_grad(x, y)
```

to get the result I expect, but in practice `y` is actually quite large, so repeating it just so the gradient is computed properly seems wasteful. I will dig into that more though.

**Comment by josevalim** [comment]
I think this makes sense because the grad is computed over y, but I would like to see if @polvalente has a different opinion.

**Comment by jyc** [comment]
I tried checking if it would still be efficient to broadcast `y` to the size of `x` in order to get a gradient with the same dimensions as `y`; I wasn't sure whether Nx would create e.g. a vector with zero stride. However it looks like the `byte_size` increases, at least with Nx.BinaryBackend and Nx.EXLABackend:

```elixir
x = ~VEC[0 0] |> vectorize(:foo)
y = ~VEC[1]
[x, y] = Nx.broadcast_vectors([x, y])
y |> Nx.byte_size()
# 16
# if another elements are added to `x`, evaluates to 24, etc.
```

So I still would be interested if there is a way to get the non-summed gradient, although I understand if it's not possible with this API.

**Comment by polvalente** [comment]
I agree with @jyc in that the grad should have the same vector shape as the output. That is, the correct result for the example should be `[1.0, 1.0]` instead of `2.0`.

The mental model I have is that `fun(vectorized[foo: 2] [1, 2])` should yield the same output as `vectorize(stack([fun(1), fun(2)]), :foo)`, which is not the case here.

**Comment by polvalente** [comment]
Memory-wise, vectorization will end up doing the explicit broadcasting, if applicable, regardless of the backend (although some backends might end up fusing things).

**Comment by jyc** [comment]
@polvalente Thanks for the reply! Sorry but just to be clear, I checked after you mentioned the mental model and it looks like `grad` returns the same result even without vectorization, so my mentioning the vectorization was a red herring:

```elixir
defmodule Foo do
  import Nx.Defn
  defn f(x, y) do
    x + y
  end

  defn f_and_grad(x, y) do
    value_and_grad(y, fn y -> Foo.f(x, y) end)
  end
end

x = ~VEC[0 1 2]
y = ~VEC[1]
Foo.f_and_grad(x, y)
# {~VEC[1, 2, 3], ~VEC[3]}
```

This is still surprising to me but at least it is consistent with and without vectorization. I will keep looking for a workaround.

**Comment by jyc** [comment]
Actually, I have confused myself! I don't believe it's a red herring because it's the other axis that is vectorized. I misunderstood. Please ignore my last comment, sorry for the noise.

**Comment by polvalente** [comment]
The problem here is that for that `Foo` module, this isn't true:

```elixir
x = Nx.tensor([0, 1, 2])
y = 1

{_, grad0} = Foo.f_and_grad(x[0], y)
{_, grad1} = Foo.f_and_grad(x[1], y)
{_, grad2} = Foo.f_and_grad(x[2], y)

expected_result = Nx.stack([grad0, grad1, grad2]) |> Nx.vectorize(:foo)

actual_result = Foo.f_and_grad(Nx.vectorize(x, :foo), y)
```

**Comment by jyc** [comment]
You are right! Sorry for the noise.

**Comment by josevalim** [comment]
Reopening because we still need to support vectorize/devectorize inside the gradient. :)

**Comment by ja-b** [comment]
Curious if this behavior is expected given the current vectorization support for gradient?

```
defmodule NaturalGasAnalyticsLib.NXAutoGradTest do
  use ExUnit.Case

  import Nx.Defn

  defn sum_elems(tensor) do
    tensor[0] + tensor[1] + tensor[2]
  end

  defn sum_elems_grad(tensor) do
    grad(tensor, &sum_elems/1)
  end

  test "basic" do
    x = Nx.iota({3, 3})
    xv = Nx.vectorize(x, :elements)

    IO.inspect(sum_elems(x))
    IO.inspect(sum_elems(xv))
    IO.inspect(sum_elems_grad(x))
    IO.inspect(sum_elems_grad(xv))
  end
end
```
(please excuse the dumb example 😅 )

All print except for the last entry, which yields this error

```
  1) test basic (NaturalGasAnalyticsLib.NXAutoGradTest)
     test/nx_autograd_test.exs:16
     ** (ArgumentError) expected length of axes (3) to match rank of shape (2)
     stacktrace:
       (nx 0.9.2) lib/nx/shape.ex:238: Nx.Shape.broadcast!/4
       (nx 0.9.2) lib/nx.ex:3782: anonymous fn/5 in Nx.broadcast/3
       (nx 0.9.2) lib/nx.ex:5408: Nx.apply_vectorized/2
       (nx 0.9.2) lib/nx/defn/grad.ex:485: Nx.Defn.Grad.grad/4
       (nx 0.9.2) lib/nx/defn/grad.ex:410: Nx.Defn.Grad.update_grads/6
       (nx 0.9.2) lib/nx/defn/grad.ex:256: Nx.Defn.Grad.recur_to_grad/4
       (elixir 1.16.3) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
       (nx 0.9.2) lib/nx/defn/grad.ex:228: Nx.Defn.Grad.recur_to_grad/4
       (elixir 1.16.3) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
       (nx 0.9.2) lib/nx/defn/grad.ex:209: Nx.Defn.Grad.to_grad/4
       (nx 0.9.2) lib/nx/defn/grad.ex:33: Nx.Defn.Grad.transform/3
       (nx 0.9.2) lib/nx/defn.ex:640: anonymous fn/2 in Nx.Defn.grad/2
       (nx 0.9.2) lib/nx/defn/compiler.ex:173: Nx.Defn.Compiler.runtime_fun/3
       (exla 0.9.1) lib/exla/defn.ex:365: anonymous fn/4 in EXLA.Defn.compile/8
       (exla 0.9.1) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
       (stdlib 5.2) timer.erl:270: :timer.tc/2
       (exla 0.9.1) lib/exla/defn.ex:363: anonymous fn/15 in EXLA.Defn.compile/8
       (exla 0.9.1) lib/exla/defn.ex:229: EXLA.Defn.__compile__/4
       (exla 0.9.1) lib/exla/defn.ex:219: EXLA.Defn.__jit__/5
       (nx 0.9.2) lib/nx/defn.ex:452: Nx.Defn.do_jit_apply/3
```

And I find myself running into this error when having a vectorized axis in the input provided tensor to the gradient, generally speaking.

**Comment by polvalente** [comment]
This is definitely part of the issue at hand. Unfortunately grad support for vectorized functions doesn't cover all cases properly.

**Comment by petrkozorezov** [comment]
> ```
>   1) test basic (NXAutoGradTest)
>      test/nx_autograd_test.exs:16
>      ** (ArgumentError) expected length of axes (3) to match rank of shape (2)
>      stacktrace:
>        (nx 0.9.2) lib/nx/shape.ex:238: Nx.Shape.broadcast!/4
>        (nx 0.9.2) lib/nx.ex:3782: anonymous fn/5 in Nx.broadcast/3
> ```
Have the same problem trying to calculate gradient over vectorized tensors.

**Comment by polvalente** [comment]
I think if Option B works, that's the preferred approach. Otherwise,  C seems to be the same as A but with code reuse. 

edit: I missed the part where B doesn't work. Let's go with C

**Comment by blasphemetheus** [comment]
right! PR should close this, I just rebased onto a new branch to catch up to main

**Comment by blasphemetheus** [comment]
The remaining failing tests on the PR for this were fixed and commits were squashed into 3. Fuzzing didn't reveal other issues and the added tests are less redundant now

**Comment by blasphemetheus** [comment]
#1697 closed  as wrong approach, working on approach pointed out in review over at https://github.com/blasphemetheus/nx/tree/fix/1533-vectorized-grad-v2

**Comment by blasphemetheus** [comment]
ok picking this back up, here's a case that I've implemented two different options for.

```elixir
x = ~VEC[1 2]  |> vectorize(:foo) # foo: 2
y = ~VEC[3 4 5] |> vectorize(:bar) # bar: 3
{gx, gy} = grad({x,y}, fn {x,y} -> sum(x*y) end)
```
Option A: gx and gy both have [foo: 2, bar: 3]
(https://github.com/blasphemetheus/nx/pull/8)

Option B: gx has [foo: 2], gy has [bar: 3]
(https://github.com/blasphemetheus/nx/pull/9)

Option B makes more sense to me, do y'all have an opinion?

**Comment by polvalente** [comment]
@blasphemetheus I think option B is the one we want! In your implementation, I think what we want is to take 1-sized slices for all vectorized axes that aren't present. So if we end up with a result that is `vectorized [foo: 3, bar: 4] shape {m, n}` and input is `vectorized [foo: 3] ...`, we should do something like:

```elixir
output
|> Nx.devectorize()
|> Nx.slice([0, 0, 0, 0], [3, 1, m, n])
|> Nx.vectorize(original_axes)
```

**Comment by blasphemetheus** [comment]
gotcha thank you pol!

I do see a downside to taking 1-sized slices for all vectorized axes that aren't present. the gradient with respect to one input often depends on the value of the other input. Slicing throws all but one of those contributions away.

```elixir
x = Nx.tensor([2.0, 5.0]) |> Nx.vectorize(:foo)
y = Nx.tensor([3.0, 4.0]) |> Nx.vectorize(:bar)
{gx, gy} = Nx.Defn.grad({x, y}, fn {x, y} -> Nx.multiply(x, y) |> Nx.sum() end)
```

The total derivative matches how Nx grad currently unbroadcasts non-vec broadcast dimensions.
```elixir
gx = [7, 7] # each element is y[bar:0] + y[bar:1] = 3 + 4 = 7
gy = [7, 7] # each element is x[foo:0] + x[foo:1] = 2 + 5 = 7
```

for a 1-sized slice approach:
```elixir
gx = [3, 3] # only y[bar:0] = 3 survives while y[bar:1] (4.0) is discarded
gy = [2, 2] # only x[foo:0] = 2 survives while x[foo:1] (5.0) is discarded
```

Slicing works when the gradient is constant across the foreign axis (for example `f = x * 5.0`). For anything that combines both inputs, the slice gives the gradient of one arbitrary slice of the loss instead of the gradient of the loss itself. This would break gradient-based optimization.

[link to a relevant test](https://github.com/blasphemetheus/nx/pull/9/changes/d0226e2aa7b2e2b800baba2905420e28d9b9cc35#diff-8ead83f6fa0272c7ab25f0d7cfc8bf7b2b0e2d0f50db26a00c31d60a6ab7e94cR5194)

**Comment by polvalente** [comment]
If slicing would throw information away, then we need to keep the results vectorized with all vector axes (as if we had thrown broadcas_vectors over the inputs before doing anything)

**Comment by blasphemetheus** [comment]
right on, I'll continue with the "approach a" branch, update some tests. I think I'll do a PR for elixir-nx's repo soon. There's a couple different failing tests that are currently skipped in the fork's PR branch. Those are sort of separate small issues that are related to vectorization. For a PR I can submit those tests but have them `@tag skip`ed and add some comments as to why. Or I can just remove them from the PR, put the tests somewhere else and file issues for these cases.

I'll do the latter, that makes more sense I think.

- #1706 (unbroadcast in the dot gradient doesn't know about vectorized axes)
- apply_vectorized tests (cholesky, triangular_solve, cond). These ops re-vectorize internally, so the boundary wrapper's devectorized recursion can't reconcile this. Could have those operation operate without internal re-vectorization or just document the limitation (#1729)
- there's an edge case where the same axis name changes meaning: input has [x: 3], output has [x: 1]. So there's the same axis name, but different sizes (#1730)
