### ISSUE TITLE
Issues with for loop

### ISSUE THREAD

**Issue by NduatiK** [elixir-nx/nx#615]
Hi all,

I am struggling to make use of the for loop in Nx when implementing a simple linear regressor. When I compile the code below, I get an error. What am I doing wrong?

```elixir
defmodule ProgrammingMlBook.LinearRegression do
  @moduledoc """
  Chapter 2 code on LinearRegression
  """
  import Nx.Defn

  defn predict(x, w) do
    Nx.multiply(x, w)
  end

  defn loss(x, y, w) do
    Nx.subtract(predict(x, w), y)
    |> Nx.power(2)
    |> Nx.mean()
  end

  def train(x, y, opts \\ []) do
    w =
      opts
      |> Keyword.get(:w, 0)
      |> Nx.tensor(type: {:f, 64})

    iterations = Keyword.get(opts, :iterations, 0)

    lr =
      opts
      |> Keyword.get(:lr, 0.01)
      |> Nx.tensor(type: {:f, 64})

    train(x, y, w, lr, iterations, 1_000_0000)
  end

  defn train(x, y, w, lr, iterations, current_error) do
    if iterations <= 0 do
      -1
    else
      iterations = iterations - 1

      for _ <- 1..iterations, reduce: w do
        w ->
          cond do
            Nx.all(Nx.less(loss(x, y, w + lr), current_error)) ->
              w + lr

            Nx.all(Nx.less(loss(x, y, w - lr), current_error)) ->
              w - lr

            true ->
              w
          end
      end
    end
  end
end
```

Error
```elixir
== Compilation error in file lib/LinearRegression/programming_ml_book.ex ==
** (CompileError) lib/LinearRegression/programming_ml_book.ex:39: invalid numerical expression:

    for _ <- Nx.Defn.Kernel.".."(1, iterations) do
      w -> cond do
          Nx.all(Nx.less(loss(x, y, Nx.add(w, lr)), current_error)) -> Nx.add(w, lr)
          Nx.all(Nx.less(loss(x, y, Nx.add(w, lr)), current_error)) -> Nx.add(w, lr)
          true -> w
        end
    reduce
      w
    end

    (nx 0.1.0) lib/nx/defn/compiler.ex:529: Nx.Defn.Compiler.compile_error!/3
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.1.0) lib/nx/defn/compiler.ex:258: Nx.Defn.Compiler.normalize/2
    (nx 0.1.0) lib/nx/defn/compiler.ex:292: anonymous fn/2 in Nx.Defn.Compiler.normalize/2
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nx 0.1.0) lib/nx/defn/compiler.ex:290: Nx.Defn.Compiler.normalize/2
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

**Comment by NduatiK** [comment]
I have also tried `Nx.reduce` and `while` so perhaps I am lacking some fundamental understanding

**Comment by josevalim** [comment]
@NduatiK `for` is currently not supported in `defn`. You need to use `while`. What have you tried?

**Comment by NduatiK** [comment]
Yes, let me share the error I had with that

**Comment by NduatiK** [comment]
Using while, I change my train function to:
```elixir
defn train(x, y, initial_w, lr, iterations, current_error) do
    if iterations <= 0 do
      -1
    else
      while {w = initial_w, i = iterations}, Nx.greater(i, 0) do
        cond do
          Nx.all(Nx.less(loss(x, y, w + lr), current_error)) ->
            {w + lr, i - 1}

          Nx.all(Nx.less(loss(x, y, w - lr), current_error)) ->
            {w - lr, i - 1}

          true ->
            {w, i - 1}
        end
      end
    end
  end
```

At runtime, when I call the function `ProgrammingMlBook.LinearRegression.train(x, y, 0, 0.01, 1, 0)` I get the error:
```elixir
** (RuntimeError) cannot build defn because expressions come from different contexts: :root and :while.

This typically happens on "while" and inside anonymous functions, which do not behave like closures inside defn. For example, this is not valid:

    defn example(t, amplifier) do
      Nx.reduce(t, 0, fn val, acc ->
        val * amplifier + acc
      end)
    end

In the example above, "amplifier" is a variable defined outside of the anonymous function, which is not allowed in defn.

    (nx 0.1.0) lib/nx/defn/expr.ex:909: Nx.Defn.Expr.merge_context!/2
    (nx 0.1.0) lib/nx/defn/expr.ex:846: anonymous fn/2 in Nx.Defn.Expr.to_exprs/1
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.1.0) lib/nx/defn/expr.ex:452: Nx.Defn.Expr.less/3
    (programming_ml_book 0.1.0) lib/LinearRegression/programming_ml_book.ex:43: anonymous fn/2 in ProgrammingMlBook.LinearRegression."__defn:train__"/6
    (nx 0.1.0) lib/nx/defn/expr.ex:273: Nx.Defn.Expr.defn_while/5
    (programming_ml_book 0.1.0) lib/LinearRegression/programming_ml_book.ex:41: ProgrammingMlBook.LinearRegression."__defn:train__"/6
```

**Comment by josevalim** [comment]
As the error message says, you need to pass all variables used in the `while` as arguments to the `while`:

```elixir
defn train(x, y, initial_w, lr, iterations, current_error) do
    if iterations <= 0 do
      -1
    else
      while {w = initial_w, i = iterations, x, y, current_error}, Nx.greater(i, 0) do
        cond do
          Nx.all(Nx.less(loss(x, y, w + lr), current_error)) ->
            {w + lr, i - 1, x, y, current_error}

          Nx.all(Nx.less(loss(x, y, w - lr), current_error)) ->
            {w - lr, i - 1, x, y, current_error}

          true ->
            {w, i - 1, x, y, current_error}
        end
      end
    end
  end
```

I will try to make the error message clearer. I can probably add some macro based analysis.

**Comment by NduatiK** [comment]
Yeah, I think I have solved it. I had to pass x, y and lr into the while loop. I also had to remove the outer if statement since it caused the following error:
```
* (KeyError) key 7 not found in: %{0 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91270>}, 1 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91271>}, 2 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91272>}, 3 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91273>}, 4 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91274>}, 5 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91275>}}
    :erlang.map_get(7, %{0 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91270>}, 1 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91271>}, 2 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91272>}, 3 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91273>}, 4 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91274>}, 5 => %EXLA.Op{builder: #Reference<0.736776192.2778071047.91257>, ref: #Reference<0.736776192.2778071047.91275>}})
    (exla 0.1.0-dev) lib/exla/defn.ex:431: EXLA.Defn.cached_recur_operator/4
    (exla 0.1.0-dev) lib/exla/defn.ex:389: EXLA.Defn.recur_operator/3
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (exla 0.1.0-dev) lib/exla/defn.ex:476: EXLA.Defn.cached_recur_operator/4
    (exla 0.1.0-dev) lib/exla/defn.ex:389: EXLA.Defn.recur_operator/3
    (exla 0.1.0-dev) lib/exla/defn.ex:1229: EXLA.Defn.token_computation/6
    (exla 0.1.0-dev) lib/exla/defn.ex:398: EXLA.Defn.cached_recur_operator/4
```

I am not sure why the if would trip up the execution plan (not implemented in Nx?)

**Comment by NduatiK** [comment]
As an aside, I initially tried using recursion but I think that caused an infinitely sized execution plan. Is there somewhere we can add a warning about that in the docs?

**Comment by josevalim** [comment]
> Yeah, I think I have solved it. I had to pass x, y and lr into the while loop. I also had to remove the outer if statement since it caused the following error:

That's a bug, I will investigate it too!

**Comment by NduatiK** [comment]
Thank you for the help, @josevalim!

**Comment by josevalim** [comment]
I will keep this open so we can have the improvements above!
