### ISSUE TITLE
(MatchError) no match of right hand side value: <<195, 154, 29, 117>>

### ISSUE THREAD

**Issue by googya** [elixir-nx/nx#641]
I'm sorry, I don't know exactly what the problem is, so I can't give a proper title, I can only use part of the information in the error report as the title

I have a tiny elixir script for a linear regression case and when running, it says:

```shell
** (MatchError) no match of right hand side value: <<2, 144, 195, 245, 124, 245, 59, 248, 159, 156, 26, 247>>
    (nx 0.1.0) lib/nx/binary_backend.ex:639: anonymous fn/10 in Nx.BinaryBackend.element_wise_bin_op/4
    (elixir 1.13.3) lib/enum.ex:4136: Enum.reduce_range/5
    (nx 0.1.0) lib/nx/binary_backend.ex:628: Nx.BinaryBackend.element_wise_bin_op/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:149: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:63: Nx.Defn.Evaluator.eval/3
    (nx 0.1.0) lib/nx/defn/evaluator.ex:30: Nx.Defn.Evaluator.__jit__/4
    (elixir 1.13.3) lib/enum.ex:4136: Enum.reduce_range/5
    matrix.exs:67: (file)
```

The code isn't very standardized, but it should work.
the code is as follows:

```elixir
Mix.install([
  {:nx, "~> 0.1.0"},
])
require IEx

defmodule Hyperspace do
  import Nx.Defn

  defn predict(x, w) do
    Nx.dot(x, w)
  end

  defn loss(x, y, w) do
    (predict(x, w) - y)
    |> Nx.power(2)
    |> Nx.mean()
  end

  defn gradient(x, y, w, lr) do
    y_hat = predict(x, w) - y
    new_w = Nx.transpose(x)
    |> Nx.dot(y_hat)
    |> Nx.multiply(2)
    |> Nx.divide(elem(x.shape, 0))
    
    w - new_w * lr
  end
  def train(x, y, iteration, lr) do
    n = elem(x.shape, 1)
    w = Nx.reshape(Nx.tensor(List.duplicate(0, n)), {n , 1})
    for _i <- 1..iteration, reduce: w do
      old_w -> gradient(x, y, old_w, lr)
    end
  end
end

# {:ok, c} = File.read("/private/tmp/a.txt")
c = """
Pollution             Healthcare            Water       Life
13.67861608           4.78591616            98.9        76.251999
25.08644703           4.48014942            100         74.254997
5.932051308           9.42230024            100         82.558998
16.45924852           11.20547328           100         81.25
28.0060253            6.0368632             86.2        71.800003
13.72387382           7.74236489            98.4        75.378998
60.33412401           4.98079638            100         76.622002
87.03455404           2.81899856            86.2        71.803001
15.20732479           7.469303              99.7        75.602997
20.03426999           5.68772158            99.7        72.504997
15.78042979           10.5947509            100         80.792
25.45071189           5.78895004            99.5        70.027
38.37472292           4.59429651            77.8        60.373001
54.13286886           3.57301481            100         69.43
"""
data = c |> String.split("\n", trim: true)  |> List.delete_at(0)  |> Enum.map(fn s -> String.split(s, " ", trim: true) end)  |> Enum.map(fn e -> Enum.map(e, fn z ->  Float.parse(z) |> elem(0) end) end)
tensor = Nx.tensor(data, names: [:y, :x])
{rows, cols} = Nx.shape(tensor)
x = tensor[x: 0..(cols - 2)]
{b, n} = x.shape
y = tensor[x: (cols - 1)] |> Nx.reshape({b, 1})
gen = List.duplicate(1, b) |> Nx.tensor() |> Nx.reshape({b, 1}) 
new_x = Nx.concatenate([gen, x], axis: 1)

w = Hyperspace.train(new_x, y, 100000, 0.001)

extract = fn e -> e |> Nx.to_flat_list() |> Enum.join(",") end
IO.puts("\nWeights #{extract.(w)}")
IO.puts("\nA few prediction:")
for i <- 0..4 do
  t = Hyperspace.predict(new_x[i], w)
  IO.puts("X[#{i}] -> #{extract.(t)} (label: #{extract.(y[i])})")
end
IEx.pry

```

**Comment by polvalente** [comment]
@googya this sounds like it could be related to #119

Could you be running into NaN or Inf somewhere else in the result?

**Comment by josevalim** [comment]
@googya can you please run it against the latest main branch and let us know if you get a different error?

**Comment by googya** [comment]
> 

I change the code and build it:
```elixir
Mix.install([
  # {:nx, "~> 0.1.0"},
  {:nx, path: "/private/tmp/nx/nx"}
])
```

The error message is different:

```shell
** (ArithmeticError) bad argument in arithmetic expression
    (nx 0.1.0) lib/nx/binary_backend.ex:654: Nx.BinaryBackend.element_divide/3
    (nx 0.1.0) lib/nx/binary_backend.ex:612: Nx.BinaryBackend."-element_wise_bin_op/4-lbc$^21/2-5-"/7
    (nx 0.1.0) lib/nx/binary_backend.ex:611: Nx.BinaryBackend.element_wise_bin_op/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:149: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:63: Nx.Defn.Evaluator.eval/3
    (elixir 1.13.3) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.1.0) lib/nx/defn/evaluator.ex:130: Nx.Defn.Evaluator.eval_apply/4
    (nx 0.1.0) lib/nx/defn/evaluator.ex:63: Nx.Defn.Evaluator.eval/3

```

**Comment by josevalim** [comment]
Oh, so it is for sure infinity/nan or division by zero issue. You can do `|> inspect_value` before `divide` to double check.

**Comment by googya** [comment]
> 

Right, I got a abnormal data:

#Nx.Tensor<
  f32[4][1]
  [
    [-6.941338408025027e36],
    [-2.134865587651564e38],
    [-4.390259901433068e37],
    [-Inf]
  ]
>
