### ISSUE TITLE
cannot invoke Nx function because it relies on two incompatible tensor implementations: Nx.Defn.Expr and EXLA.Backend

### ISSUE THREAD

**Issue by noozo** [elixir-nx/nx#776]
When `run`ning train_data on a variation of the `credit_card_fraud` axon example, i'm getting this error:

``` 
...
Epoch: 26, Batch: 0, loss: 8.8533077
Epoch: 27, Batch: 0, loss: 8.6933546
Epoch: 28, Batch: 0, loss: 8.5427504
Epoch: 29, Batch: 0, loss: 8.4041109
** (Axon.CompilerError) error while building prediction for dense:

** (Axon.CompilerError) error while building prediction for dropout:

** (Axon.CompilerError) error while building prediction for dense:

** (RuntimeError) cannot invoke Nx function because it relies on two incompatible tensor implementations: Nx.Defn.Expr and EXLA.Backend. You may need to call Nx.backend_transfer/1 (or Nx.backend_copy/1) on one or both of them to transfer them to a common implementation



    (nx 0.2.0) lib/nx/shared.ex:421: Nx.Shared.pick_struct/2
    (nx 0.2.0) lib/nx.ex:8030: Nx.dot/6
    (axon 0.1.0-dev) lib/axon/layers.ex:109: Axon.Layers."__defn:dense__"/3
    (axon 0.1.0-dev) lib/axon/compiler.ex:374: Axon.Compiler.recur_predict_fun/5
    (axon 0.1.0-dev) lib/axon/compiler.ex:182: Axon.Compiler.to_predict_fun/5
    (axon 0.1.0-dev) lib/axon/compiler.ex:521: Axon.Compiler.recur_predict_fun/5
    (axon 0.1.0-dev) lib/axon/compiler.ex:182: Axon.Compiler.to_predict_fun/5
    (elixir 1.13.2) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

Assuming it might be related to `to_batched_list` not being supported on EXLA (not implemented yet), but could be not the case.

Here's my full code:
```
defmodule Fuel do
  require Axon
  require Logger

  # @epochs 1000
  @epochs 30
  @learning_rate 0.01
  @loss :mean_absolute_error
  @dropout_rate 0.1

  @input_columns [
    "Cylinders",
    "Displacement",
    "Horsepower"
  ]

  defp data do
    types = [{"MPG", :float},
    {"Cylinders", :float},
    {"Displacement", :float},
    {"Horsepower", :float},
    {"Weight", :float},
    {"Acceleration", :float},
    {"Model" , :float},
    {"Country", :float}, # 1 USA, 2 Europe, 3 Japan
    {"Name", :string}]

    names = Enum.map(types, fn {name, _type} -> name end)
    df = Explorer.DataFrame.read_csv!("./auto-mpg.data", dtypes: types, header?: false, names: names)

    {train_df, test_df} = split_train_test(df, 0.8)

    IO.puts("Training Samples: #{inspect(Explorer.DataFrame.n_rows(train_df))}")
    IO.puts("Testing Samples: #{inspect(Explorer.DataFrame.n_rows(test_df))}")
    IO.write("\n\n")

    {train_features, train_targets} = split_features_targets(train_df)
    {test_features, test_targets} = split_features_targets(test_df)

    train_features = normalize_data(train_features)
    test_features = normalize_data(test_features)

    {
      {df_to_tensor(train_features), df_to_tensor(train_targets)},
      {df_to_tensor(test_features), df_to_tensor(test_targets)}
    }
  end

  def run_example do
    EXLA.set_as_nx_default([:tpu, :cuda, :rocm, :host])

    model =
      Axon.input({nil, Enum.count(@input_columns)})
      |> Axon.dense(10)
      |> Axon.dropout(rate: @dropout_rate)
      |> Axon.dense(1)

    optimizer = Axon.Optimizers.adam(@learning_rate)

    {train, test} = data()
    {train_inputs, train_targets} = train
    {test_inputs, test_targets} = test

    batched_train_inputs = train_inputs
    |> Nx.backend_transfer(Nx.BinaryBackend)
    |> Nx.to_batched_list(32)
    batched_train_targets = train_targets
    |> Nx.backend_transfer(Nx.BinaryBackend)
    |> Nx.to_batched_list(32)

    batched_train = Stream.zip(batched_train_inputs, batched_train_targets)

    batched_test_inputs = test_inputs
    |> Nx.backend_transfer(Nx.BinaryBackend)
    |> Nx.to_batched_list(32)
    batched_test_targets = test_targets
    |> Nx.backend_transfer(Nx.BinaryBackend)
    |> Nx.to_batched_list(32)

    batched_test = Stream.zip(batched_test_inputs, batched_test_targets)

    model
    |> train_model(@loss, optimizer, batched_train)
    |> then(&test_model(model, &1, batched_test))
  end

  defp df_to_tensor(df) do
    df
    |> Explorer.DataFrame.names()
    |> Enum.map(&Explorer.Series.to_tensor(df[&1]) |> Nx.new_axis(-1))
    |> Nx.concatenate(axis: 1)
  end

  defp normalize(name),
    do: fn df -> Explorer.Series.divide(df[name], Explorer.Series.max(df[name])) end

  defp normalize_data(df) do
    df
    |> Explorer.DataFrame.names()
    |> Map.new(&{&1, normalize(&1)})
    |> then(&Explorer.DataFrame.mutate(df, &1))
  end

   defp split_train_test(df, portion) do
    num_examples = Explorer.DataFrame.n_rows(df)
    num_train = ceil(portion * num_examples)
    num_test = num_examples - num_train

    {
      Explorer.DataFrame.slice(df, 0, num_train),
      Explorer.DataFrame.slice(df, num_train, num_test)
    }
  end

  defp split_features_targets(df) do
    features = Explorer.DataFrame.select(df, @input_columns, :keep)
    targets = Explorer.DataFrame.select(df, ["MPG"], :keep)

    {features, targets}
  end


  defp summarize(%Axon.Loop.State{metrics: metrics} = state) do
    IO.write("\n\n")
    IO.inspect(metrics)
    {:continue, state}
  end

  defp metrics(loop) do
    loop
    |> Axon.Loop.metric(:accuracy)
  end

  defp test_model(model, model_state, test_data) do
    model
    |> Axon.Loop.evaluator(model_state)
    |> metrics()
    |> Axon.Loop.handle(:epoch_completed, &summarize/1)
    |> Axon.Loop.run(test_data)
    |> IO.inspect()
  end

  defp train_model(model, loss, optimizer, train_data) do
    model
    |> Axon.Loop.trainer(loss, optimizer)
    |> Axon.Loop.run(train_data, epochs: @epochs)
  end

  def predict({model, trained_params}, car_input) do
    model
    |> Axon.predict(trained_params, car_input)
    |> Nx.to_flat_list()
    |> List.first()
  end

  def scalar(tensor) do
    tensor |> Nx.to_flat_list() |> List.first()
  end
end
```

`|> Nx.backend_transfer(Nx.BinaryBackend)` is being added to the batched data, due the missing implementation of `to_batched_list` in EXLA.

Sample from `auto-mpg.data`:
```
18.0,8,307.0,130.0,3504.0,12.0,70,1,"chevrolet chevelle malibu"
15.0,8,350.0,165.0,3693.0,11.5,70,1,"buick skylark 320"
18.0,8,318.0,150.0,3436.0,11.0,70,1,"plymouth satellite"
16.0,8,304.0,150.0,3433.0,12.0,70,1,"amc rebel sst"
17.0,8,302.0,140.0,3449.0,10.5,70,1,"ford torino"
```

config/config.exs
```
import Config
config :nx, :default_backend, EXLA.Backend
config :nx, :default_defn_options, [compiler: EXLA]
```

mix.exs
```
 defp deps do
    [
      {:axon, "~> 0.1.0-dev", github: "elixir-nx/axon", branch: "main"},
      {:exla, "~> 0.2.0"},
      # {:torchx, "~> 0.2"},
      {:nx, "~> 0.2.0", override: true},
      {:explorer, "~> 0.1.1"}
    ]
  end
```

**Comment by noozo** [comment]
Just confirmed that the same happens on the vanilla Axon example: https://github.com/elixir-nx/axon/blob/main/examples/structured/credit_card_fraud.exs

Again, had to add `Nx.backend_transfer` (or `Nx.backend_copy`) to make it be able to train, so the two issues (EXLA `to_batched_list` not implemented) might be related.

**Comment by noozo** [comment]
Also tried to revert back to the credit_card_fraud example mix dependencies:

```
{:axon, "~> 0.1.0-dev", github: "elixir-nx/axon"},
  {:exla, "~> 0.1.0-dev", github: "elixir-nx/nx", sparse: "exla"},
  {:nx, path: "~> 0.1.0-dev", github: "elixir-nx/nx", sparse: "nx", override: true},
  {:explorer, "~> 0.1.0-dev", github: "elixir-nx/explorer"}
```

But that also does not work, as Axon no longer seems to have that version on github (or something related):

```
 iex -S mix
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Unchecked dependencies for environment dev:
* exla (https://github.com/elixir-nx/nx.git)
  the dependency does not match the requirement "~> 0.1.0-dev", got "0.2.0"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by josevalim** [comment]
Closing in favor of https://github.com/elixir-nx/axon/issues/244. Thanks @jonatanklosko !
