### ISSUE TITLE
Nx.Defn.while 

### ISSUE THREAD

**Issue by RD314** [elixir-nx/nx#818]
I have encountered a strange behaviour of the while loop. Probably it is just my misunderstanding of the concept, however, you can judge yourself.

I have created a small example with super simplified iterative power method to replicate the behaviour. (The code is not mathematically perfect, however the issue for discussion is the reason for the runtime error). The code and error is below:
```
Nx.make_diagonal(Nx.tensor([1.0,2.0,3.8])), 
|> PowerMethod.compute( Nx.tensor([2.2,3.5,1.1]) )
```

```
** (RuntimeError) The parameter of condition and body, the result of the body, and init must all have the same shape; got Condition: (p0: (token[], (u8[], f32[3], f32[3,3], f32[]))) -> pred[]; body: (p0: (token[], (u8[], f32[3], f32[3,3], f32[]))) -> (token[], (pred[], f32[3], f32[3,3], f32[])); init: (token[], (pred[], f32[3], f32[3,3], f32[]))..
    (exla 0.2.1) lib/exla/op.ex:804: EXLA.Op.unwrap!/1
    (exla 0.2.1) lib/exla/op.ex:109: EXLA.Op.get_shape/1
    (exla 0.2.1) lib/exla/builder.ex:23: EXLA.Builder.build/1
    (exla 0.2.1) lib/exla/defn.ex:247: EXLA.Defn.to_root_computation/5
    (exla 0.2.1) lib/exla/defn.ex:324: anonymous fn/8 in EXLA.Defn.compile/7
    (exla 0.2.1) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (exla 0.2.1) lib/exla/defn.ex:319: EXLA.Defn.compile/7
    (exla 0.2.1) lib/exla/defn.ex:224: EXLA.Defn.__jit__/5
    (nx 0.2.1) lib/nx/defn/compiler.ex:252: Nx.Defn.Compiler.__runtime__/2
```

```
defmodule PowerMethod do
import Nx.Defn

defn compute( matrix, x) do

  while {exit_condition = Nx.greater(2,1), x, matrix, itercount = Nx.tensor(1.0)}, Nx.greater(exit_condition, 0) do

    new_x = Nx.dot(matrix, x)

    norm_scale =
      new_x
      |> Nx.dot(new_x)
      |> Nx.sqrt()

    normalised_x = Nx.divide(new_x, norm_scale)

    error_norm =
      normalised_x
      |> Nx.subtract(x)
      |> Nx.power(2)
      |> Nx.sum()
      |> Nx.sqrt()

    limit = 1.0e-6

    precision_cond = Nx.greater(error_norm, limit)
    iter_count_cond = Nx.less(Nx.add(itercount, 1.0), 5)

    new_exit_condition =
      precision_cond
      |> Nx.logical_and(iter_count_cond)

    {new_exit_condition, normalised_x, matrix, Nx.add(itercount, 1.0)}
    end
  end
end

```

**Comment by josevalim** [comment]
Looks like a bug as Elixir was supposed to raise here. So we are either failing to catch something or there is a bug somewhere. :)

**Comment by RD314** [comment]
I found the workaround... using `cond do`. I have no clue why this works :-)

```
defmodule PowerMethod do
import Nx.Defn

defn compute( matrix, x) do

  while {exit_condition = Nx.greater(2,1), x, matrix, itercount = Nx.tensor(1.0)}, Nx.greater(exit_condition, 0) do

    new_x = Nx.dot(matrix, x)

    norm_scale =
      new_x
      |> Nx.dot(new_x)
      |> Nx.sqrt()

    normalised_x = Nx.divide(new_x, norm_scale)

    error_norm =
      normalised_x
      |> Nx.subtract(x)
      |> Nx.power(2)
      |> Nx.sum()
      |> Nx.sqrt()

    limit = 1.0e-6

    precision_cond = Nx.greater(error_norm, limit)
    iter_count_cond = Nx.less(Nx.add(itercount, 1.0), 5)

    new_exit_condition =
      precision_cond
      |> Nx.logical_and(iter_count_cond)

    coded_exit_conditions =
      cond do
        Nx.greater(new_exit_condition,0) -> Nx.greater(2,1)
        true -> Nx.greater(1,2)
      end

    {coded_exit_conditions, normalised_x, matrix, Nx.add(itercount, 1.0)}

    end
  end
end

```

**Comment by josevalim** [comment]
Fixed in main and v0.2 branch.
