### ISSUE TITLE
Nx.map `nil.ref/0 is undefined` error

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#881]
```elixir
defmodule Test do
  import Nx.Defn
  defn replace_nan(v) do
    if Nx.is_nan(v) do 0.0 else v end
  end
end
Test.replace_nan(Nx.tensor(:nan))
Nx.map(Nx.tensor([:nan]), &Test.replace_nan/1)
```
Works as expected with default (binary) backend, but fails with EXLA on the last line
```
** (UndefinedFunctionError) function nil.ref/0 is undefined. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map
    nil.ref()
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (exla 0.3.0) lib/exla/op.ex:72: EXLA.Op.tuple/2
    (exla 0.3.0) lib/exla/defn.ex:1604: EXLA.Defn.to_if_branch/5
    (exla 0.3.0) lib/exla/defn.ex:1535: EXLA.Defn.to_if/5
    (exla 0.3.0) lib/exla/defn.ex:499: EXLA.Defn.cached_recur_operator/4
    (exla 0.3.0) lib/exla/defn.ex:472: EXLA.Defn.recur_operator/3
    (exla 0.3.0) lib/exla/defn.ex:1456: EXLA.Defn.recur_composite/4
```

**Comment by seanmor5** [comment]
This is definitely a bug, but you should consider using Nx.select instead of Nx.map!

Nx.select(Nx.is_nan(x), 0.0, x)

**Comment by polvalente** [comment]
From what I've looked, it seems there's some sort of cache miss happening where it isn't expected to. I'll try to look some more during the week.
