### ISSUE TITLE
Cumulative_sum is not working on 0.4.0

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#970]
I'm trying to migrate to 0.4.0 and see that sometime `cumulative_sum` fails with
```
** (ArgumentError) expected default implementation to match template #Nx.Tensor<
  f32[time: 1440]
  
  Nx.Defn.Expr
  parameter a:0   f32[1440]
>, got: #Nx.Tensor<
  f32[1440]
  
  Nx.Defn.Expr
  parameter a:0          f32[1440]
  b = cumulative_sum a   f32[1440]
>
    (nx 0.4.0) lib/nx/shared.ex:516: Nx.Shared.ensure_optional_compatible!/2
    (nx 0.4.0) lib/nx/defn/compiler.ex:138: Nx.Defn.Compiler.runtime_fun/3
    (exla 0.4.0) lib/exla/defn.ex:368: anonymous fn/2 in EXLA.Defn.compile/7
    (exla 0.4.0) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 3.17.2) timer.erl:166: :timer.tc/1
    (exla 0.4.0) lib/exla/defn.ex:366: EXLA.Defn.compile/7
    (exla 0.4.0) lib/exla/defn.ex:262: EXLA.Defn.__compile__/4
    (exla 0.4.0) lib/exla/defn.ex:248: EXLA.Defn.__jit__/5
```

I've tried to trace `Nx.Shared.ensure_optional_compatible!` and I see that impl losses axis name

```
# 05:46:48 #PID<0.133.0> Livebook.Runtime.Evaluator.init/1
# Nx.Shared.ensure_optional_compatible!(#Nx.Tensor<
  f32[1440]
  
  Nx.Defn.Expr
  parameter a:0          f32[1440]
  b = cumulative_sum a   f32[1440]
>, #Nx.Tensor<
  f32[time: 1440]
  
  Nx.Defn.Expr
  parameter a:0   f32[1440]
>)

# 05:46:48 #PID<0.133.0> Livebook.Runtime.Evaluator.init/1
# Nx.Shared.ensure_optional_compatible!/2 -> {:error, %ArgumentError{message: "expected default implementation to match template #Nx.Tensor<\n  f32[time: 1440]\n  \n  Nx.Defn.Expr\n  parameter a:0   f32[1440]\n>, got: #Nx.Tensor<\n  f32[1440]\n  \n  Nx.Defn.Expr\n  parameter a:0          f32[1440]\n  b = cumulative_sum a   f32[1440]\n>"}}
```

It works in my test cases, but does not in the notebook with real data. I can not make minimal example yet, but maybe you can understand what is going on without it, or I can give you more information?

**Comment by josevalim** [comment]
I believe I know what it is. :) I will play with it later today!
