### ISSUE TITLE
Grad for Nx.clip

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#971]
```elixir
Mix.install(
  [
    {:nx, "~> 0.4.0"},
    {:exla, "~> 0.4.0"}
  ],
  config: [
    nx: [
      default_backend: EXLA.Backend,
      default_defn_options: [compiler: EXLA]
    ]
  ]
)

defmodule T do
  import Nx.Defn

  defn g(t, n) do
    grad(n, &fun(t, &1))
  end

  defn fun(t, n) do
    Nx.clip(t, -n, +n)
  end
end

t=Nx.tensor([0.4, 0.1, -0.3, 0.2])
T.g(t, 0.11)
```

Fails with 
```
** (ArgumentError) cannot broadcast tensor of dimensions {4} to {}
    (nx 0.4.0) lib/nx/shape.ex:1073: Nx.Shape.broadcast_axes/2
    (nx 0.4.0) lib/nx.ex:2826: Nx.broadcast/3
    (nx 0.4.0) lib/nx/defn/grad.ex:166: Nx.Defn.Grad.to_grad/4
    (nx 0.4.0) lib/nx/defn/grad.ex:28: Nx.Defn.Grad.transform/3
    (nx 0.4.0) lib/nx/defn.ex:620: anonymous fn/2 in Nx.Defn.grad/2
    (nx 0.4.0) lib/nx/defn/compiler.ex:138: Nx.Defn.Compiler.runtime_fun/3
    (exla 0.4.0) lib/exla/defn.ex:368: anonymous fn/2 in EXLA.Defn.compile/7
    (exla 0.4.0) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
```

**Comment by josevalim** [comment]
Good find. We definitely don't have tests for when the gradient is the min/max.

**Comment by petrkozorezov** [comment]
It seems to be the same problem with `Nx.select`, when the gradient is the predicate.

**Comment by polvalente** [comment]
> It seems to be the same problem with `Nx.select`, when the gradient is the predicate.

What do you mean by this, @petrkozorezov?
